name: CI

on: [push]

jobs:
  sast_scan:
    name: Running Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -r -ll -ii . -f json -o bandit.report.json

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        name: bandit-findings
        path: bandit.report.json

  build-image:
    name: Building Docker image and scan it
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4.3.0
      with:
        docker_version: '20.10.7'

    - name: Docker build
      run: docker build -f Dockerfile -t myapp:latest .

#    - name: Docker Login
 #     uses: docker/login-action@v3.4.0
  #    with:
   #     username: polocto
    #    password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker Scout
      uses: docker/scout-action@v1.17.1
      with:
        command: quickview,cves
        dockerhub-user: polocto
        dockerhub-password: ${{ secrets.DOCKER_TOKEN }}
        format: json
        output: scout.report.json
        exit-code: true
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        name: scout-findings
        path: scout.report.json
  
    
            
