name: CI

on: [push]

jobs:
  sast_scan:
    name: Running Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -r -ll -ii . -f json -o bandit.report.json

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        name: bandit-findings
        path: bandit.report.json
  
          
